import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\Cleaned_Data_Project1.csv")
df['Date'] = pd.to_datetime(df['Date'])
print("EDA Week 2 Project.")
tp_summary = df['TotalPrice'].describe()
print(f"Count of Transactions: {int(tp_summary['count'])}")
print(f"Mean (Average):        ${tp_summary['mean']:.2f}")
print(f"Median (50th Percent):  ${df['TotalPrice'].median():.2f}")
print(f"Minimum (Floor):       ${tp_summary['min']:.2f}")
print(f"Q1 (25th Percentile):  ${tp_summary['25%']:.2f}")
print(f"Q3 (75th Percentile):  ${tp_summary['75%']:.2f}")
print(f"Maximum (Ceiling):     ${tp_summary['max']:.2f}")
print(f"Data Skewness:         {df['TotalPrice'].skew():.3f}")
print("\nSales by Product Category")
product_sales = df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)
print(product_sales)
sns.set_theme(style="darkgrid")
# Graph A: Distribution Plot (Histogram + Density Curve)
plt.clf()
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(df['TotalPrice'], kde=True, color='teal', bins=30, ax=ax)
ax.set_title('Distribution of Total Price (Positive Skewness)', fontsize=14, pad=15)
ax.set_xlabel('Total Price ($)', fontsize=12)
ax.set_ylabel('Transaction Count', fontsize=12)
plt.tight_layout()
plt.savefig('total_price_distribution.png')
print("\n[Saved Chart 1] total_price_distribution.png")
# Graph B: Box Plot (Five-Number Summary Visualized)
plt.clf()
fig, ax = plt.subplots(figsize=(8, 4))
sns.boxplot(x=df['TotalPrice'], color='lightcoral', ax=ax)
ax.set_title('Box Plot of Total Price (Identifying Outliers)', fontsize=14, pad=15)
ax.set_xlabel('Total Price ($)', fontsize=12)
plt.tight_layout()
plt.savefig('total_price_boxplot.png')
print("[Saved Chart 2] total_price_boxplot.png")
# Graph C: Sales Trend Over Time (Temporal Analysis)
df['YearMonth'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('YearMonth')['TotalPrice'].sum().reset_index()
monthly_sales['YearMonth'] = monthly_sales['YearMonth'].astype(str)
plt.clf()
fig, ax = plt.subplots(figsize=(10, 5))
sns.lineplot(data=monthly_sales, x='YearMonth', y='TotalPrice', marker='o', color='darkblue', linewidth=2.5, ax=ax)
ax.set_title('Monthly Total Sales Trend (Temporal Analysis)', fontsize=14, pad=15)
ax.set_xlabel('Month', fontsize=12)
ax.set_ylabel('Total Revenue ($)', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('monthly_sales_trend.png')
print("[Saved Chart 3] monthly_sales_trend.png")
# Graph D: Ranking Comparisons (Bar Chart)
product_revenue = df.groupby('Product')['TotalPrice'].sum().reset_index().sort_values(by='TotalPrice', ascending=False)
plt.clf()
fig, ax = plt.subplots(figsize=(9, 5))
sns.barplot(data=product_revenue, x='Product', y='TotalPrice', palette='viridis', ax=ax)
ax.set_title('Total Revenue by Product Category (Comparison)', fontsize=14, pad=15)
ax.set_xlabel('Product', fontsize=12)
ax.set_ylabel('Total Revenue ($)', fontsize=12)
plt.tight_layout()
plt.savefig('product_revenue_comparison.png')
print("[Saved Chart 4] product_revenue_comparison.png")
# Graph E: Bivariate Relationship (Scatter Plot)
plt.clf()
fig, ax = plt.subplots(figsize=(8, 5))
sns.scatterplot(data=df, x='ItemsInCart', y='TotalPrice', alpha=0.6, color='purple', ax=ax)
ax.set_title('Relationship Between Items in Cart and Total Price', fontsize=14, pad=15)
ax.set_xlabel('Number of Items in Cart', fontsize=12)
ax.set_ylabel('Total Price ($)', fontsize=12)
plt.tight_layout()
plt.savefig('cart_items_vs_total_price.png')
print("[Saved Extra Chart] cart_items_vs_total_price.png")
# Graph F: Correlation Heatmap (Multivariate Analysis)
plt.clf()
fig, ax = plt.subplots(figsize=(8, 6))
numeric_df = df[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']]
correlation_matrix = numeric_df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, ax=ax)
ax.set_title('Correlation Matrix of Numeric Features', fontsize=14, pad=15)
plt.tight_layout()
plt.savefig('correlation_heatmap.png')
print("[Saved Extra Chart] correlation_heatmap.png")
print("\nAll EDA charts have been compiled and exported successfully!")